
services:
  app1:
    build: ./sample1
    container_name: app1
    ports:
      - "10001:80"   # host:container
    restart: always

  app2:
    build: ./sample2
    container_name: app2
    ports:
      - "10002:80"
    restart: always
  
  app3:
    build: ./sample3
    container_name: app3
    ports:
      - "10003:80"
    restart: always

#variables-- APP_NAME , IMAGE_NAME -> FOLDERNAME WHERE DOCKER FILE IS PRESENT, 